apiVersion: batch/v1
kind: Job
metadata:
  name: busybox
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["date"]
      restartPolicy: Never
